### ISSUE TITLE
Where is the latest version? 

### ISSUE THREAD

**Issue by rraub** [ASU/asu-header#4]
It looks like this repo is out of date compared to the latest webspark release. Is this github repo going to be used going forward?

**Comment by jrounsav** [comment]
Hey Ryan, the master branch is currently in use by another group. For the time being please see use the 4.x in order to get the latest header version.

https://github.com/ASU/asu-header/tree/4.x

**Comment by rraub** [comment]
Gotcha! I wasn't sure if there was another version maintained elsewhere. Thanks!
